name: "CI Pipeline"
on: 
  push:
    branches:
      - main
    tags:
      - 'release-*'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Conan Install
        run: batteries/script/run-with-docker.sh make BUILD_TYPE=Release install
      - name: Conan Build
        run: batteries/script/run-with-docker.sh make BUILD_TYPE=Release build
      - name: Conan Test
        run: batteries/script/run-with-docker.sh make BUILD_TYPE=Release test
