name: "CI Pipeline"
on:
  pull_request:
    branches:    
      - main    
  push:
    branches:
      - main
    tags:
      - 'release-*'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Secret test
        env:
          RELEASE_CONAN_REMOTE: ${{ vars.RELEASE_CONAN_REMOTE }}
          RELEASE_CONAN_LOGIN_USERNAME: ${{ vars.RELEASE_CONAN_LOGIN_USERNAME }}
          RELEASE_CONAN_PASSWORD: ${{ secrets.RELEASE_CONAN_PASSWORD }}
        run: env | grep -i conan > ~/the_conan_output.txt
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Conan Install
        run: script/run-with-docker.sh make BUILD_TYPE=Release install
      - name: Conan Build
        run: script/run-with-docker.sh make BUILD_TYPE=Release build
      - name: Conan Test
        run: script/run-with-docker.sh make BUILD_TYPE=Release test
