name: "CI Pipeline"
on: 
  push:
    branches:
      - main
    tags:
      - 'release-*'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Conan Install
        run: make BUILD_TYPE=Release install
